cvar_t	*vr_snapturn_angle;
cvar_t	*vr_reloadtimeoutms;
cvar_t	*vr_positional_factor;
cvar_t	*vr_walkdirection;
cvar_t	*vr_movement_multiplier;
cvar_t	*vr_weapon_pitchadjust;
cvar_t	*vr_lasersight;
cvar_t	*vr_control_scheme;
cvar_t	*vr_teleport;
